In [1]:
# Original dataset: https://www.consumerfinance.gov/data-research/hmda/historic-data/?geo=ny&records=all-records&field_descriptions=labels

# 1) Iteration by chunks: Null values
    The dataset is massive so we will deal with it by chunks.
    We split the dataset in chunks of x size, then iterate by each chunk and finally we summarize the total column's null values.

In [2]:
import pandas as pd

In [3]:
# We force to show all the records
pd.set_option('display.max_rows', None) 

# We create a dictionary to keep all null values from the different chunks
total_null_values = None

# Iterate across the different chunks directly from the dataset
for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):
    chunk_null_values = chunk.isnull().sum()
    
    if total_null_values is None:
        total_null_values = chunk_null_values
    else:
        total_null_values += chunk_null_values
    
    # Total null values per chunk
    print(f'Null values per column in this chunk:\n{chunk_null_values}\n')

# Total null values for the whole dataset
print(f'Total null values per column in the entire dataset:\n{total_null_values}')

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\1901377790.py:8: DtypeWarning: Columns (36,38,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):

Null values per column in this chunk:
as_of_year                             0
respondent_id                          0
agency_name                            0
agency_abbr                            0
agency_code                            0
loan_type_name                         0
loan_type                              0
property_type_name                     0
property_type                          0
loan_purpose_name                      0
loan_purpose                           0
owner_occupancy_name                   0
owner_occupancy                        0
loan_amount_000s                       0
preapproval_name                       0
preapproval                            0
action_taken_name                      0
action_taken                           0
msamd_name                          6174
msamd                               6167
state_name                             0
state_abbr                             0
state_code                             0
county_name                            1
county_code                            1
census_tract_number                   39
applicant_ethnicity_name               0
applicant_ethnicity                    0
co_applicant_ethnicity_name            0
co_applicant_ethnicity                 0
applicant_race_name_1                  0
applicant_race_1                       0
applicant_race_name_2              99474
applicant_race_2                   99474
applicant_race_name_3              99952
applicant_race_3                   99952
applicant_race_name_4              99992
applicant_race_4                   99992
applicant_race_name_5              99994
applicant_race_5                   99994
co_applicant_race_name_1               0
co_applicant_race_1                    0
co_applicant_race_name_2           99848
co_applicant_race_2                99848
co_applicant_race_name_3           99987
co_applicant_race_3                99987
co_applicant_race_name_4           99999
co_applicant_race_4                99999
co_applicant_race_name_5          100000
co_applicant_race_5               100000
applicant_sex_name                     0
applicant_sex                          0
co_applicant_sex_name                  0
co_applicant_sex                       0
applicant_income_000s               9789
purchaser_type_name                    0
purchaser_type                         0
denial_reason_name_1               85560
denial_reason_1                    85560
denial_reason_name_2               96720
denial_reason_2                    96720
denial_reason_name_3               99399
denial_reason_3                    99399
rate_spread                        97518
hoepa_status_name                      0
hoepa_status                           0
lien_status_name                       0
lien_status                            0
edit_status_name                  100000
edit_status                       100000
sequence_number                   100000
population                            39
minority_population                   39
hud_median_family_income              39
tract_to_msamd_income                 39
number_of_owner_occupied_units        39
number_of_1_to_4_family_units         39
application_date_indicator        100000
dtype: int64

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\1901377790.py:8: DtypeWarning: Columns (34,36,38,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):

Null values per column in this chunk:
as_of_year                             0
respondent_id                          0
agency_name                            0
agency_abbr                            0
agency_code                            0
loan_type_name                         0
loan_type                              0
property_type_name                     0
property_type                          0
loan_purpose_name                      0
loan_purpose                           0
owner_occupancy_name                   0
owner_occupancy                        0
loan_amount_000s                       0
preapproval_name                       0
preapproval                            0
action_taken_name                      0
action_taken                           0
msamd_name                          3421
msamd                               3418
state_name                             0
state_abbr                             0
state_code                             0
county_name                            3
county_code                            3
census_tract_number                   58
applicant_ethnicity_name               0
applicant_ethnicity                    0
co_applicant_ethnicity_name            0
co_applicant_ethnicity                 0
applicant_race_name_1                  0
applicant_race_1                       0
applicant_race_name_2              99625
applicant_race_2                   99625
applicant_race_name_3              99963
applicant_race_3                   99963
applicant_race_name_4              99993
applicant_race_4                   99993
applicant_race_name_5              99994
applicant_race_5                   99994
co_applicant_race_name_1               0
co_applicant_race_1                    0
co_applicant_race_name_2           99889
co_applicant_race_2                99889
co_applicant_race_name_3           99992
co_applicant_race_3                99992
co_applicant_race_name_4           99999
co_applicant_race_4                99999
co_applicant_race_name_5           99999
co_applicant_race_5                99999
applicant_sex_name                     0
applicant_sex                          0
co_applicant_sex_name                  0
co_applicant_sex                       0
applicant_income_000s              11343
purchaser_type_name                    0
purchaser_type                         0
denial_reason_name_1               93183
denial_reason_1                    93183
denial_reason_name_2               98569
denial_reason_2                    98569
denial_reason_name_3               99773
denial_reason_3                    99773
rate_spread                        97481
hoepa_status_name                      0
hoepa_status                           0
lien_status_name                       0
lien_status                            0
edit_status_name                  100000
edit_status                       100000
sequence_number                   100000
population                            58
minority_population                   58
hud_median_family_income              58
tract_to_msamd_income                 58
number_of_owner_occupied_units        58
number_of_1_to_4_family_units         58
application_date_indicator        100000
dtype: int64

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\1901377790.py:8: DtypeWarning: Columns (34,36,38,42,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):

Null values per column in this chunk:
as_of_year                             0
respondent_id                          0
agency_name                            0
agency_abbr                            0
agency_code                            0
loan_type_name                         0
loan_type                              0
property_type_name                     0
property_type                          0
loan_purpose_name                      0
loan_purpose                           0
owner_occupancy_name                   0
owner_occupancy                        0
loan_amount_000s                       0
preapproval_name                       0
preapproval                            0
action_taken_name                      0
action_taken                           0
msamd_name                         13801
msamd                              13791
state_name                             0
state_abbr                             0
state_code                             0
county_name                          154
county_code                          154
census_tract_number                  258
applicant_ethnicity_name               0
applicant_ethnicity                    0
co_applicant_ethnicity_name            0
co_applicant_ethnicity                 0
applicant_race_name_1                  0
applicant_race_1                       0
applicant_race_name_2              99699
applicant_race_2                   99699
applicant_race_name_3              99974
applicant_race_3                   99974
applicant_race_name_4              99993
applicant_race_4                   99993
applicant_race_name_5              99997
applicant_race_5                   99997
co_applicant_race_name_1               0
co_applicant_race_1                    0
co_applicant_race_name_2           99900
co_applicant_race_2                99900
co_applicant_race_name_3           99996
co_applicant_race_3                99996
co_applicant_race_name_4           99998
co_applicant_race_4                99998
co_applicant_race_name_5           99998
co_applicant_race_5                99998
applicant_sex_name                     0
applicant_sex                          0
co_applicant_sex_name                  0
co_applicant_sex                       0
applicant_income_000s              13205
purchaser_type_name                    0
purchaser_type                         0
denial_reason_name_1               89445
denial_reason_1                    89445
denial_reason_name_2               98100
denial_reason_2                    98100
denial_reason_name_3               99670
denial_reason_3                    99670
rate_spread                        97666
hoepa_status_name                      0
hoepa_status                           0
lien_status_name                       0
lien_status                            0
edit_status_name                  100000
edit_status                       100000
sequence_number                   100000
population                           258
minority_population                  258
hud_median_family_income             258
tract_to_msamd_income                258
number_of_owner_occupied_units       258
number_of_1_to_4_family_units        258
application_date_indicator        100000
dtype: int64

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\1901377790.py:8: DtypeWarning: Columns (36,38,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):

Null values per column in this chunk:
as_of_year                             0
respondent_id                          0
agency_name                            0
agency_abbr                            0
agency_code                            0
loan_type_name                         0
loan_type                              0
property_type_name                     0
property_type                          0
loan_purpose_name                      0
loan_purpose                           0
owner_occupancy_name                   0
owner_occupancy                        0
loan_amount_000s                       0
preapproval_name                       0
preapproval                            0
action_taken_name                      0
action_taken                           0
msamd_name                          8870
msamd                               8866
state_name                             0
state_abbr                             0
state_code                             0
county_name                          475
county_code                          475
census_tract_number                  551
applicant_ethnicity_name               0
applicant_ethnicity                    0
co_applicant_ethnicity_name            0
co_applicant_ethnicity                 0
applicant_race_name_1                  0
applicant_race_1                       0
applicant_race_name_2              99561
applicant_race_2                   99561
applicant_race_name_3              99957
applicant_race_3                   99957
applicant_race_name_4              99989
applicant_race_4                   99989
applicant_race_name_5              99992
applicant_race_5                   99992
co_applicant_race_name_1               0
co_applicant_race_1                    0
co_applicant_race_name_2           99864
co_applicant_race_2                99864
co_applicant_race_name_3           99985
co_applicant_race_3                99985
co_applicant_race_name_4           99997
co_applicant_race_4                99997
co_applicant_race_name_5           99997
co_applicant_race_5                99997
applicant_sex_name                     0
applicant_sex                          0
co_applicant_sex_name                  0
co_applicant_sex                       0
applicant_income_000s              11346
purchaser_type_name                    0
purchaser_type                         0
denial_reason_name_1               86415
denial_reason_1                    86415
denial_reason_name_2               96966
denial_reason_2                    96966
denial_reason_name_3               99499
denial_reason_3                    99499
rate_spread                        98278
hoepa_status_name                      0
hoepa_status                           0
lien_status_name                       0
lien_status                            0
edit_status_name                  100000
edit_status                       100000
sequence_number                   100000
population                           551
minority_population                  551
hud_median_family_income             551
tract_to_msamd_income                551
number_of_owner_occupied_units       551
number_of_1_to_4_family_units        551
application_date_indicator        100000
dtype: int64

Null values per column in this chunk:
as_of_year                            0
respondent_id                         0
agency_name                           0
agency_abbr                           0
agency_code                           0
loan_type_name                        0
loan_type                             0
property_type_name                    0
property_type                         0
loan_purpose_name                     0
loan_purpose                          0
owner_occupancy_name                  0
owner_occupancy                       0
loan_amount_000s                      0
preapproval_name                      0
preapproval                           0
action_taken_name                     0
action_taken                          0
msamd_name                         4970
msamd                              4965
state_name                            0
state_abbr                            0
state_code                            0
county_name                          62
county_code                          62
census_tract_number                 169
applicant_ethnicity_name              0
applicant_ethnicity                   0
co_applicant_ethnicity_name           0
co_applicant_ethnicity                0
applicant_race_name_1                 0
applicant_race_1                      0
applicant_race_name_2             46727
applicant_race_2                  46727
applicant_race_name_3             46881
applicant_race_3                  46881
applicant_race_name_4             46896
applicant_race_4                  46896
applicant_race_name_5             46899
applicant_race_5                  46899
co_applicant_race_name_1              0
co_applicant_race_1                   0
co_applicant_race_name_2          46860
co_applicant_race_2               46860
co_applicant_race_name_3          46893
co_applicant_race_3               46893
co_applicant_race_name_4          46901
co_applicant_race_4               46901
co_applicant_race_name_5          46902
co_applicant_race_5               46902
applicant_sex_name                    0
applicant_sex                         0
co_applicant_sex_name                 0
co_applicant_sex                      0
applicant_income_000s              7888
purchaser_type_name                   0
purchaser_type                        0
denial_reason_name_1              40790
denial_reason_1                   40790
denial_reason_name_2              45575
denial_reason_2                   45575
denial_reason_name_3              46696
denial_reason_3                   46696
rate_spread                       45895
hoepa_status_name                     0
hoepa_status                          0
lien_status_name                      0
lien_status                           0
edit_status_name                  46902
edit_status                       46902
sequence_number                   46902
population                          169
minority_population                 169
hud_median_family_income            169
tract_to_msamd_income               169
number_of_owner_occupied_units      169
number_of_1_to_4_family_units       169
application_date_indicator        46902
dtype: int64

Total null values per column in the entire dataset:
as_of_year                             0
respondent_id                          0
agency_name                            0
agency_abbr                            0
agency_code                            0
loan_type_name                         0
loan_type                              0
property_type_name                     0
property_type                          0
loan_purpose_name                      0
loan_purpose                           0
owner_occupancy_name                   0
owner_occupancy                        0
loan_amount_000s                       0
preapproval_name                       0
preapproval                            0
action_taken_name                      0
action_taken                           0
msamd_name                         37236
msamd                              37207
state_name                             0
state_abbr                             0
state_code                             0
county_name                          695
county_code                          695
census_tract_number                 1075
applicant_ethnicity_name               0
applicant_ethnicity                    0
co_applicant_ethnicity_name            0
co_applicant_ethnicity                 0
applicant_race_name_1                  0
applicant_race_1                       0
applicant_race_name_2             445086
applicant_race_2                  445086
applicant_race_name_3             446727
applicant_race_3                  446727
applicant_race_name_4             446863
applicant_race_4                  446863
applicant_race_name_5             446876
applicant_race_5                  446876
co_applicant_race_name_1               0
co_applicant_race_1                    0
co_applicant_race_name_2          446361
co_applicant_race_2               446361
co_applicant_race_name_3          446853
co_applicant_race_3               446853
co_applicant_race_name_4          446894
co_applicant_race_4               446894
co_applicant_race_name_5          446896
co_applicant_race_5               446896
applicant_sex_name                     0
applicant_sex                          0
co_applicant_sex_name                  0
co_applicant_sex                       0
applicant_income_000s              53571
purchaser_type_name                    0
purchaser_type                         0
denial_reason_name_1              395393
denial_reason_1                   395393
denial_reason_name_2              435930
denial_reason_2                   435930
denial_reason_name_3              445037
denial_reason_3                   445037
rate_spread                       436838
hoepa_status_name                      0
hoepa_status                           0
lien_status_name                       0
lien_status                            0
edit_status_name                  446902
edit_status                       446902
sequence_number                   446902
population                          1075
minority_population                 1075
hud_median_family_income            1075
tract_to_msamd_income               1075
number_of_owner_occupied_units      1075
number_of_1_to_4_family_units       1075
application_date_indicator        446902
dtype: int64

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\1901377790.py:8: DtypeWarning: Columns (36,38,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):

# 2) Sampling for exploration:
For an easier exploration, sampled a tiny part of the whole.

In [4]:
df = pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv')

# Sample
df_sample = df.sample(n=12000, random_state=42)  

# Save the dataset
df_sample.to_csv('C:/Users/nonox/hmda_2017_ny_sampled.csv', index=False)

print("Sampled dataset saved to 'C:/Users/nonox/hmda_2017_ny_sampled.csv'")

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\1043214581.py:1: DtypeWarning: Columns (34,36,38,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv')

Sampled dataset saved to 'C:/Users/nonox/hmda_2017_ny_sampled.csv'

In [5]:
pd.set_option('display.max_rows', None)
print(df_sample.describe())

       as_of_year   agency_code     loan_type  property_type  loan_purpose  \
count     12000.0  12000.000000  12000.000000   12000.000000  12000.000000
mean       2017.0      6.879917      1.290000       1.034833      1.809417
std           0.0      2.286540      0.581603       0.223512      0.927002
min        2017.0      1.000000      1.000000       1.000000      1.000000
25%        2017.0      7.000000      1.000000       1.000000      1.000000
50%        2017.0      7.000000      1.000000       1.000000      1.000000
75%        2017.0      9.000000      1.000000       1.000000      3.000000
max        2017.0      9.000000      4.000000       3.000000      3.000000

       owner_occupancy  loan_amount_000s   preapproval  action_taken  \
count     12000.000000      12000.000000  12000.000000  12000.000000
mean          1.115833        346.848750      2.828250      2.518083
std           0.354156       1396.116964      0.438484      1.854443
min           1.000000          1.000000      1.000000      1.000000
25%           1.000000        108.000000      3.000000      1.000000
50%           1.000000        216.000000      3.000000      1.000000
75%           1.000000        383.000000      3.000000      4.000000
max           3.000000      99999.000000      3.000000      6.000000

              msamd  ...  edit_status_name  edit_status  sequence_number  \
count  11020.000000  ...               0.0          0.0              0.0
mean   32167.064973  ...               NaN          NaN              NaN
std     9710.247378  ...               NaN          NaN              NaN
min    10580.000000  ...               NaN          NaN              NaN
25%    35004.000000  ...               NaN          NaN              NaN
50%    35614.000000  ...               NaN          NaN              NaN
75%    35614.000000  ...               NaN          NaN              NaN
max    48060.000000  ...               NaN          NaN              NaN

         population  minority_population  hud_median_family_income  \
count  11971.000000         11971.000000              11971.000000
mean    4814.235152            31.076043              79842.210342
std     1971.385135            29.464924              16697.010025
min       15.000000             0.000000              62100.000000
25%     3494.000000             8.090000              68200.000000
50%     4586.000000            19.360001              73700.000000
75%     5966.500000            43.750000              83100.000000
max    28926.000000           100.000000             110800.000000

       tract_to_msamd_income  number_of_owner_occupied_units  \
count           11971.000000                    11971.000000
mean              114.940613                     1196.577730
std                50.383399                      608.013037
min                 0.000000                        0.000000
25%                86.560001                      723.000000
50%               106.000000                     1181.000000
75%               130.529999                     1618.000000
max               346.989990                     4682.000000

       number_of_1_to_4_family_units  application_date_indicator
count                   11971.000000                         0.0
mean                     1545.848467                         NaN
std                       787.779799                         NaN
min                         0.000000                         NaN
25%                      1001.000000                         NaN
50%                      1538.000000                         NaN
75%                      2054.000000                         NaN
max                      6541.000000                         NaN

[8 rows x 45 columns]

# 3) Iteration by chunks: "No co-applicants"
    a) First step in our data selection is to try to reduce the number of record as soon as possible.
    b) By focusing on "No co-aplicants" we significantly reduce the number of records.
    c) Our focus is on single individuals, we only take "No co-applicat" records.

In [6]:
# Initialize an empty DataFrame to store the filtered data
filtered_df = pd.DataFrame()

# Processing the CSV file in chunks
for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):
    # Filter the chunk where "co_applicant_ethnicity_name" is "No co-applicant"
    filtered_chunk = chunk[chunk['co_applicant_ethnicity_name'] == 'No co-applicant']
    
    # Append the filtered chunk to the filtered_df DataFrame
    filtered_df = pd.concat([filtered_df, filtered_chunk])

# New CSV file
filtered_df.to_csv('C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv', index=False)

print(f"Filtered dataset saved to '{'C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv'}'")


#https://www.geeksforgeeks.org/how-to-create-an-empty-dataframe-and-append-rows-columns-to-it-in-pandas/

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\511449127.py:5: DtypeWarning: Columns (36,38,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):
C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\511449127.py:5: DtypeWarning: Columns (34,36,38,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):
C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\511449127.py:5: DtypeWarning: Columns (34,36,38,42,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):
C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\511449127.py:5: DtypeWarning: Columns (36,38,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):
C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\511449127.py:5: DtypeWarning: Columns (36,38,44,46) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('C:/Users/nonox/hmda_2017_ny.csv', chunksize=100000):

Filtered dataset saved to 'C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv'

In [7]:
# Checking new dimension:

pd.set_option('display.max_rows', None) 
df = pd.read_csv('C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv')

# Shape
print(df.shape, '\n')

# Null values
print(df.isnull().sum())

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\2794338369.py:4: DtypeWarning: Columns (34,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv')

(242296, 78)

as_of_year                             0
respondent_id                          0
agency_name                            0
agency_abbr                            0
agency_code                            0
loan_type_name                         0
loan_type                              0
property_type_name                     0
property_type                          0
loan_purpose_name                      0
loan_purpose                           0
owner_occupancy_name                   0
owner_occupancy                        0
loan_amount_000s                       0
preapproval_name                       0
preapproval                            0
action_taken_name                      0
action_taken                           0
msamd_name                         21138
msamd                              21120
state_name                             0
state_abbr                             0
state_code                             0
county_name                          455
county_code                          455
census_tract_number                  658
applicant_ethnicity_name               0
applicant_ethnicity                    0
co_applicant_ethnicity_name            0
co_applicant_ethnicity                 0
applicant_race_name_1                  0
applicant_race_1                       0
applicant_race_name_2             241083
applicant_race_2                  241083
applicant_race_name_3             242175
applicant_race_3                  242175
applicant_race_name_4             242271
applicant_race_4                  242271
applicant_race_name_5             242278
applicant_race_5                  242278
co_applicant_race_name_1               0
co_applicant_race_1                    0
co_applicant_race_name_2          242296
co_applicant_race_2               242296
co_applicant_race_name_3          242296
co_applicant_race_3               242296
co_applicant_race_name_4          242296
co_applicant_race_4               242296
co_applicant_race_name_5          242296
co_applicant_race_5               242296
applicant_sex_name                     0
applicant_sex                          0
co_applicant_sex_name                  0
co_applicant_sex                       0
applicant_income_000s              21702
purchaser_type_name                    0
purchaser_type                         0
denial_reason_name_1              208345
denial_reason_1                   208345
denial_reason_name_2              235066
denial_reason_2                   235066
denial_reason_name_3              241147
denial_reason_3                   241147
rate_spread                       236153
hoepa_status_name                      0
hoepa_status                           0
lien_status_name                       0
lien_status                            0
edit_status_name                  242296
edit_status                       242296
sequence_number                   242296
population                           658
minority_population                  658
hud_median_family_income             658
tract_to_msamd_income                658
number_of_owner_occupied_units       658
number_of_1_to_4_family_units        658
application_date_indicator        242296
dtype: int64

# Random checking: 

 1) Statistics

In [8]:
pd.set_option('display.max_rows', None)
df = pd.read_csv('C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv')
print(df.describe())

C:\Users\nonox\AppData\Local\Temp\ipykernel_21348\330022007.py:2: DtypeWarning: Columns (34,36,38) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/nonox/hmda_2017_ny_no_co_applicant.csv')

       as_of_year    agency_code      loan_type  property_type   loan_purpose  \
count    242296.0  242296.000000  242296.000000  242296.000000  242296.000000
mean       2017.0       6.731539       1.255328       1.050591       1.852362
std           0.0       2.329735       0.557420       0.277363       0.921090
min        2017.0       1.000000       1.000000       1.000000       1.000000
25%        2017.0       5.000000       1.000000       1.000000       1.000000
50%        2017.0       7.000000       1.000000       1.000000       1.000000
75%        2017.0       9.000000       1.000000       1.000000       3.000000
max        2017.0       9.000000       4.000000       3.000000       3.000000

       owner_occupancy  loan_amount_000s    preapproval   action_taken  \
count    242296.000000      2.422960e+05  242296.000000  242296.000000
mean          1.143927      3.635772e+02       2.818255       2.261940
std           0.394643      7.259435e+03       0.441463       1.596415
min           1.000000      1.000000e+00       1.000000       1.000000
25%           1.000000      9.100000e+01       3.000000       1.000000
50%           1.000000      1.850000e+02       3.000000       1.000000
75%           1.000000      3.520000e+02       3.000000       3.000000
max           3.000000      3.400000e+06       3.000000       8.000000

               msamd  ...  edit_status_name  edit_status  sequence_number  \
count  221176.000000  ...               0.0          0.0              0.0
mean    32224.861269  ...               NaN          NaN              NaN
std      9760.299127  ...               NaN          NaN              NaN
min     10580.000000  ...               NaN          NaN              NaN
25%     35004.000000  ...               NaN          NaN              NaN
50%     35614.000000  ...               NaN          NaN              NaN
75%     35614.000000  ...               NaN          NaN              NaN
max     48060.000000  ...               NaN          NaN              NaN

          population  minority_population  hud_median_family_income  \
count  241638.000000        241638.000000             241638.000000
mean     4739.386814            32.598630              78840.872710
std      1924.512498            30.463047              16091.655921
min         0.000000             0.000000              62100.000000
25%      3402.000000             8.470000              68200.000000
50%      4515.000000            20.480000              73700.000000
75%      5913.000000            47.209999              83100.000000
max     28926.000000           100.000000             110800.000000

       tract_to_msamd_income  number_of_owner_occupied_units  \
count          241638.000000                   241638.000000
mean              111.968936                     1153.332717
std                50.227476                      608.146784
min                 0.000000                        0.000000
25%                83.910004                      670.000000
50%               103.720001                     1126.000000
75%               127.349998                     1579.000000
max               346.989990                     4682.000000

       number_of_1_to_4_family_units  application_date_indicator
count                  241638.000000                         0.0
mean                     1515.089092                         NaN
std                       795.438084                         NaN
min                         0.000000                         NaN
25%                       962.000000                         NaN
50%                      1502.000000                         NaN
75%                      2019.000000                         NaN
max                      6541.000000                         NaN

[8 rows x 49 columns]

In [9]:

# 2. :

    # "property_type_name"

print(df['property_type_name'].value_counts())

property_type_name
One-to-four family dwelling (other than manufactured housing)    233539
Manufactured housing                                               5256
Multifamily dwelling                                               3501
Name: count, dtype: int64

# 5) Irrelevant columns:
    Apart from consider only records with "no_co-applicant"; We delete irrelevant columns


    'census_tract_number',                  
    'as_of_year',                          
    'respondent_id',
    'agency_name',                        
    'agency_abbr',                        
    'agency_code',                         
    'property_type',
    'owner_occupancy_name',
    'owner_occupancy',
    'preapproval_name',
    'preapproval',
    'state_name',
    'state_code',
    'state_abbr',
    'county_name',  
    'county_code',       
    'co_applicant_ethnicity_name',            
    'co_applicant_ethnicity',                                                         
    'applicant_race_2',
    'applicant_race_name_2',
    'applicant_race_name_3',             
    'applicant_race_3',             
    'applicant_race_name_4',
    'applicant_race_4',   
    'applicant_race_name_5',             
    'applicant_race_5',   
    'co_applicant_race_name_1',               
    'co_applicant_race_1',
    'co_applicant_race_name_2',
    'co_applicant_race_2', 
    'co_applicant_race_name_3', 
    'co_applicant_race_3',
    'co_applicant_race_name_4',
    'co_applicant_race_4',
    'co_applicant_race_4',               
    'co_applicant_race_name_5',          
    'co_applicant_race_5',               
    'co_applicant_sex_name',                  
    'co_applicant_sex',   
    'purchaser_type_name',
    'purchaser_type',                         
    'hoepa_status_name',                      
    'hoepa_status',
    'edit_status_name',                  
    'edit_status',
    'sequence_number',
    'population',
    'number_of_owner_occupied_units',       
    'number_of_1_to_4_family_units',        
    'application_date_indicator'

In [10]:
print(df['action_taken_name'].value_counts(), '\n')


print(df['denial_reason_name_1'].value_counts())

action_taken_name
Loan originated                                        132815
Application denied by financial institution             44972
Application withdrawn by applicant                      28299
Loan purchased by the institution                       14734
File closed for incompleteness                          11915
Application approved but not accepted                    9555
Preapproval request denied by financial institution         5
Preapproval request approved but not accepted               1
Name: count, dtype: int64

denial_reason_name_1
Debt-to-income ratio                              10395
Credit history                                     8637
Collateral                                         5948
Credit application incomplete                      3859
Other                                              2813
Insufficient cash (downpayment, closing costs)      924
Unverifiable information                            905
Employment history                                  403
Mortgage insurance denied                            67
Name: count, dtype: int64

# 6) Filtering columns:

#### Looking at "action_taken" column:
###### Our target is approved/denied. Therefore we will keep only:

1) Loan originated                                        111541
2) Application denied by financial institution             32229
3) Application approved but not accepted                    9555

###### Hence, from "action_taken" column we will get rid off:
1) Application withdrawn by applicant                      28299
2) Loan purchased by the institution                       14734
3) File closed for incompleteness                          11915
4) Preapproval request denied by financial institution         5
5) Preapproval request approved but not accepted               1

#### From the column "denial_reason_name_1":
1) We will get rid of "Credit application incomplete"

In [11]:
df = df[(df['denial_reason_name_1'] != "Credit application incomplete") &

        (df['action_taken_name'] != "Application withdrawn by applicant") &
        (df['action_taken_name'] != "Loan purchased by the institution") & 
        (df['action_taken_name'] != "File closed for incompleteness") &
        (df['action_taken_name'] != "Preapproval request denied by financial institution") &
        (df['action_taken_name'] != 'Preapproval request approved but not accepted')]

# Random checking

In [12]:
print(df['action_taken_name'].value_counts())

action_taken_name
Loan originated                                132815
Application denied by financial institution     41113
Application approved but not accepted            9555
Name: count, dtype: int64

# 7) Approved vs Denied
    We rename and reorganize the different records we have on "action_taken_name"

In [13]:
df['action_taken'] = df['action_taken_name'].replace({
    'Loan originated': 'approved', 
    'Application approved but not accepted': 'approved',
    'Application denied by financial institution': 'denied'
})

In [14]:
print(df['action_taken'].value_counts())

action_taken
approved    142370
denied       41113
Name: count, dtype: int64

In [15]:
print("Column names in the dataset:")
print(df.columns)

Column names in the dataset:
Index(['as_of_year', 'respondent_id', 'agency_name', 'agency_abbr',
       'agency_code', 'loan_type_name', 'loan_type', 'property_type_name',
       'property_type', 'loan_purpose_name', 'loan_purpose',
       'owner_occupancy_name', 'owner_occupancy', 'loan_amount_000s',
       'preapproval_name', 'preapproval', 'action_taken_name', 'action_taken',
       'msamd_name', 'msamd', 'state_name', 'state_abbr', 'state_code',
       'county_name', 'county_code', 'census_tract_number',
       'applicant_ethnicity_name', 'applicant_ethnicity',
       'co_applicant_ethnicity_name', 'co_applicant_ethnicity',
       'applicant_race_name_1', 'applicant_race_1', 'applicant_race_name_2',
       'applicant_race_2', 'applicant_race_name_3', 'applicant_race_3',
       'applicant_race_name_4', 'applicant_race_4', 'applicant_race_name_5',
       'applicant_race_5', 'co_applicant_race_name_1', 'co_applicant_race_1',
       'co_applicant_race_name_2', 'co_applicant_race_2',
       'co_applicant_race_name_3', 'co_applicant_race_3',
       'co_applicant_race_name_4', 'co_applicant_race_4',
       'co_applicant_race_name_5', 'co_applicant_race_5', 'applicant_sex_name',
       'applicant_sex', 'co_applicant_sex_name', 'co_applicant_sex',
       'applicant_income_000s', 'purchaser_type_name', 'purchaser_type',
       'denial_reason_name_1', 'denial_reason_1', 'denial_reason_name_2',
       'denial_reason_2', 'denial_reason_name_3', 'denial_reason_3',
       'rate_spread', 'hoepa_status_name', 'hoepa_status', 'lien_status_name',
       'lien_status', 'edit_status_name', 'edit_status', 'sequence_number',
       'population', 'minority_population', 'hud_median_family_income',
       'tract_to_msamd_income', 'number_of_owner_occupied_units',
       'number_of_1_to_4_family_units', 'application_date_indicator'],
      dtype='object')

# 8) Feature Selection

In [16]:
df = df[

        ['loan_type_name',
        'property_type_name',
        'loan_purpose_name',
        'loan_amount_000s',
        'action_taken',
        'msamd_name',
        'applicant_ethnicity_name', 
        'applicant_race_name_1',
        'applicant_sex_name',
        'applicant_income_000s', 
        'denial_reason_name_1',
        'denial_reason_name_2',
        'denial_reason_name_3', 
        'rate_spread',
        'lien_status_name',
        'minority_population',
        'hud_median_family_income',
        'tract_to_msamd_income']

        ]

In [17]:
df.to_csv('C:/Users/nonox/hmdaNY27082024_2.csv', index=False)

print(f"Dataset saved to '{'C:/Users/nonox/hmdaNY27082024_2.csv'}'")

Dataset saved to 'C:/Users/nonox/hmdaNY27082024_2.csv'

    Original dataset: https://www.consumerfinance.gov/data-research/hmda/historic-data/?geo=ny&records=all-records&field_descriptions=labels
    
# So far from original dataset: 
1) Selected "no co-applicant" records from the column "co_applicant_ethnicity_name"
2) Filter columns:
    - action_taken_name
    - denial_reason_name_1
3) Created the column "action_taken":
    - df['action_taken'] = df['action_taken_name'].replace({
    'Loan originated': 'approved', 
    'Application approved but not accepted': 'approved',
    'Application denied by financial institution': 'denied'
})  
4) First feature selection:
    - df = df[

        ['loan_type_name',
        'property_type_name',
        'loan_purpose_name',
        'loan_amount_000s',
        'action_taken',
        'msamd_name',
        'applicant_ethnicity_name', 
        'applicant_race_name_1',
        'applicant_sex_name',
        'applicant_income_000s', 
        'denial_reason_name_1',
        'denial_reason_name_2',
        'denial_reason_name_3', 
        'rate_spread',
        'lien_status_name',
        'minority_population',
        'hud_median_family_income',
        'tract_to_msamd_income']

        ]
5) Excluded "Credit application incomplete" records from the column "denial_reason_name_1"